Repository phantom-profile/storages_manage_service, pull requests merged in 2023-07, with the labels that each got.

#3 task 2: added redis client
  requirements.txt
  storages_manage_service/lib/__init__.py
  storages_manage_service/lib/redis_client.py
Labels: lib

#5 Task 4 create first views
  README.md
  storage/admin.py
  storage/migrations/0001_initial.py
  storage/models.py
  storage/templates/storage/index.html
  storage/urls.py
  storage/views.py
  storages_manage_service/settings.py
  storages_manage_service/urls.py
Labels: django-backend

#7 task 7 added base.html
  requirements.txt
  storage/templates/storage/index.html
  storages_manage_service/settings.py
  storages_manage_service/urls.py
  templates/base.html
Labels: django-backend, frontend

#8 task 6
  README.md
  storage/templates/storage/detail.html
  storage/templates/storage/index.html
  storage/views.py
Labels: django-backend, frontend

#4 Task 3 get todays weather service
  README.md
  lib/weather_service.py
Labels: lib

#9 task 8 - added navbar and footer with icon
  static/truck_icon.png
  storage/templates/storage/detail.html
  storage/templates/storage/index.html
  storage/urls.py
  storages_manage_service/settings.py
  templates/base.html
Labels: frontend

#10 task 9 - updated query to more efficient and removed old code
  main.py
  storage/templates/storage/index.html
  storage/tests.py
  storage/urls.py
  storage/views.py
Labels: django-backend

#12 Task 10 create storage
  README.md
  storage/forms.py
  storage/templates/storage/index.html
  storage/urls.py
  storage/views.py
  storages_manage_service/urls.py
Labels: django-backend, frontend

#11 task 11 - added sorting backend
  lib/filter_storages_params.py
  storage/forms.py
  storage/templates/storage/index.html
  storage/views.py
Labels: django-backend, frontend

#14 task 14 - fixed indentation
  storage/templates/storage/detail.html
  storage/templates/storage/index.html
Labels: frontend

#13 Task 12 add form errors representation
  lib/forms_factory.py
  requirements.txt
  storage/forms.py
  storage/templates/storage/index.html
  storage/views.py
  storages_manage_service/settings.py
  templates/base.html
  templates/form_fields.html
Labels: django-backend, frontend, lib

#16 Task 16 - add simple ajax weather api
  static/current_weather.js
  storage/templates/storage/index.html
  storage/urls.py
  storage/views.py
  templates/base.html
Labels: django-backend, frontend

#6 Task 5 create auth system
  storages_manage_service/settings.py
  storages_manage_service/urls.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/templates/registration/login.html
  users/templates/registration/register.html
  users/urls.py
  users/views.py
Labels: django-backend, frontend

#17 Task 13 create logger
  .gitignore
  lib/logger.py
Labels: lib

#19 Task 18 master creating model
  users/migrations/0001_initial.py
  users/migrations/0002_alter_creditcard_expires_at_alter_creditcard_vendor.py
  users/migrations/0003_alter_creditcard_card_number_and_more.py
  users/migrations/0004_creditcard_card_uuid_alter_creditcard_bank_and_more.py
  users/models.py
  users/templates/index.html
  users/urls.py
  users/views.py
Labels: django-backend, frontend

#20 Task 19 create profile page
  static/user_without_photo.png
  templates/base.html
  users/templates/profile.html
  users/urls.py
  users/views.py
Labels: django-backend, frontend

#21 task 21 - replaced Form with ModelForm
  storage/forms.py
  storage/models.py
  users/urls.py
Labels: django-backend
